spring:
 application:
   name: AuthService
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/mydb
  username: root
  password: sanket
 main:
   allow-circular-references: true

 jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
server:
  port: 8080
